#!/bin/bash

args="$@"

echo $(date +'%b %d %H:%M:%S') udev-whitelist: blocked device: "$args" >> /var/log/udev-whitelist.log

if [ -x "/usr/bin/notify-send" ]; then
	#find the user for the X display
	# https://stackoverflow.com/a/49533938

	display=":$(ls -1 /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"
	user=$(who | grep '('$display')' | awk '{print $1}')

	if [ -n "$user" ]; then
		uid=$(id -u $user)
		sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus notify-send --expire-time=8000 "udev whitelist" "blocked device: $args"
	fi
fi

exit 0
